### ISSUE TITLE
Accept to upload photos

### ISSUE THREAD

**Issue by kotar03** [zyamoji/meat_scale#1]
plz :pray:

**Comment by zyamoji** [comment]
Thank you, I'll try! 👍

**Comment by zyamoji** [comment]
Now added photo upload feature! 🎉 
But uploaded photo is too big...
I'll set max photo width or height.

**Comment by zyamoji** [comment]
I did it! 9f1b01d8cf4117d8eeeaec19e330f56d1cf0cf0f
LGTM

**Comment by kotar03** [comment]
Congrats and many thanks!

**Comment by zyamoji** [comment]
Thanks a lot!
